apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: argo-events-kustomize-installation
    namespace: argocd

spec:
    project: default

    source:
        repoURL: https://github.com/Archisman-Mridha/kubernetes-cicd
        targetRevision: HEAD
        path: kubernetes/installations/kustomize/argo-events

    destination:
        server: https://kubernetes.default.svc
        namespace: argo-events

    syncPolicy:
        automated:
            prune: true
            selfHeal: true