apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: general
    namespace: argocd
    annotations:
        argocd-image-updater.argoproj.io/image-list: archismanmridha/demo-server
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-credentials
        argocd-image-updater.argoproj.io/git-branch: main

spec:
    project: default

    source:
        repoURL: https://github.com/Archisman-Mridha/kubernetes-cicd
        targetRevision: HEAD
        path: kubernetes/general
        directory:
            recurse: true

    destination:
        server: https://kubernetes.default.svc
        namespace: "*"

    syncPolicy:
        automated:
            prune: true
            selfHeal: true