apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: github-credentials
    namespace: argocd
spec:
    encryptedData:
        password: AgB8MlrzJFoPULfnCsVbZtA+FxcBIcVklWHVVvgyeo8w8ufjRDVBHeJZbMjexPf5brABoIaWuyNaFx1T+I6bkNOVBFy8LG5dxS+MNrUQHif5wMYpsI6Ce+r/V9ZpMeLM0kiZBNfkUCZpM0M+MP5uvTs5N7Ej+ZdShKXK5pU7nTlf0sAndobG0DZ0RBlREqFMPzHXsURy1H9lJm7RdibEfjRNmoNc/NaBsGovGS1S4f5LXhEVeiONZeXYqnmMVGOK3UIn5gWkp6HiBNjaiVtWkDrJ/aYa3kxAfzP+4br3MgCuAVMcRhMVNQ57dizdA9SvSFrd2ASXeAZnjesRyKAMfI5GDxdgAoys7eX+o+MCE1FmhJnhfpOD0usTA+8cxAD3qWRhQ5aJhQcoHckHoGfy9f5V//2PfxyhxrTS1XIq3GNJXJXFKOBCmGRp6rmrinSh1nCiLsIF47rrBS9MDKLUNTpyBdZ/yrx2c4k+OHvJO02W1aFgHIiM42hVb7eGvvIdDYK01SPRhpNI+Cb2DD7e2PFEkm/9BSiwHdFvUIg+aG4jGc64+iM4VwolKUEHJLCDJlQzdQrZ4HyO+Q3+1y0ZK41tmBmQAg0b/q+rqX1gfNUqE5gWjcw3YTlT0OASBOi8EgsVQeuwSN6FwxqrXPEtGAyx5HpFy4G06t59/1r+3YIyHnMfN2hDnyIj5gcufavDIxAxOzidRncrZFlmfHFU8t4wbMn5MQIYrfYtPZh5GkgyMDMDSiQwO4yL
        username: AgCvftPzm6xAiHm3Z5Vp22eAJzcy8AnOCYFFLbwY4aTkqc68lXgMoXy0GbYeXtt1uCcH045Hdi4u+lncUUxki1YxK7BrjzW6+xbNGZJf8+vziKfTnXQNp/9wQRuYIXEuYJIDcfO2jKbXqvwDs29qFZ/H3+yjS6Mu1YSEvRevvmkf0QYhfvrTcUHudJqX4ias4ZlcD6hgbCs3ECBadgd7h8NMCfkG5d6Bb8lsY31ZYjNbZJEWkfvUtid9MK7Us/YholIkDx+tC5Cl/iwC/Ezx9cQQBsO6EpAibzZDSjqGfJObDYBvWdUHbYmAmr7A1KIV9wqZcqyvV+gqlz57wUQIRxrBBujvyGC6elKRq2idKJOPYkcPMCzdxwn+M5KaJwdjq+37adTREfEZt7cZIB76HSz/bJ39PW7ZURPb5oR61ljNwG/QVYMsceyXoIhAm4LrZ1bElN3sXFpSMM6ag31dBzgpADO6e/0iUcofbpe/nOkEBvC+ktt5JNVjtsLhlcS7eV4fZ+24B7vn1XlXTPqY3cDdJ/aGVnac97Tqv2S0Mwo0wgl6H75l1abeDdKoVrRjUoQw5YLoqWq/jysVsj5PEKKRVRQu+k1Vb7jKt0NqRuZP7OWTdqmkF+LZGNhCpJAngdArqInejQW867PQOy/QC9MCzj2fFbrOwzTX/DiofYWB/tHZ297koQq34wtDBP87qfPoaZgFYTwalLZ4eNUpQ677
    template:
        metadata:
            creationTimestamp: null
            name: github-credentials
            namespace: argocd
        type: Opaque
