apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: github-credentials
    namespace: argocd
spec:
    encryptedData:
        password: AgBCBdRHB0B1KBkRsbWNWcHqsxr96k+isEkmFNABQp5/hMxFpoJITJJejHP8fo+2fUDjVPZZcZfPYdrasKqku79tWy7Z098mOa5QWsE8FiP4NJUFg2YJXr6qb1UIrOAkUrX5WBof551TqTHHsuf48mBOxW4l1Ep+ajVZAIYjFqGwbSd1AGIoa1gWCLwdWWwgmonLcGEM+XZoVqIvi8HbzFKlStP738IbXwYXiUtFhrvjF4NJDqTJd3Zp8/sBDEyNZ8vhqW5sQfG2KWH/pfwJ67YSzqo5USxn32bND3ebaY+2RqrlZQHauRDc6UJ7JKAxXOfW7lowapf8637V3DIZ21Er8YklvZuvOvpH6fhqGM5ZPnUPEGwlRuDGlKqEXgAivcAEqvPzMPQHYRm4YKTWLau1UWhd9YfMao8rde/ttZ+GUdLy+UV4vHi1kpa94TypqOqr6J7SSJxPAd5ZDAen5Nr1/Yv2uVGDkxjAL3wVjCtEbWCVqXb9ov7vktYlnm3kgZXCuW/pMNAoBXXFuMMki4Sikir7zIhIEyDNYHqbb3X+iWrXfElWcAzs/qO/wkvCuieERBolrLLnRzhYq/4XJfwS2BGfU2G9Cu+w0Tedps5+3Y1JDlqumkvhlfzhkDuQnCSWrrozMkAREV7EZ4mZl219ByV/X+sXa2HYKN3u26QtiYMovDXQKPBQgn4LMSthH3L6Huh97hRG9SE0JdVRcJZVpKmRpvaAN8/Adz2WRe9SKVK6uls3qkBd
        username: AgDDB1VNi1KU0fLUmGbjjCOY5Aime5/Ks8bN8/NUFZRVlypUqi1J2qHr/e8U9g4+CqWgNrF0tO5VWNeoFKpsqedSgT16UqOZbjcHvCYUVg+oAnVtnAP+mpK/9xLgB3fu2LgyGzMTABd5znCjZ5aGsgAP0WPDrU7FnR+TwlZOhxwUL9EJKgzJZWemzyxHu/aiWiY+2aJ6SKM7Ec5GJW37NNybAmgo7gDTf20RK46epqpruMWe8FFYf/I5GKoOkqsi8W3am9DMx/F6mQVV459Tvpc27k4ic+shPsQ8D+5A18gAl7mdk0Uj6udywS6cug3R5Ll82lyCmatwkMVO6tOhIrBTLxZS9pgqqYGOAoNZ2B/VPDaO18c/O+zBy50ZUmR4aegO+E/3AWy5jJDdv6J6WS/UF0OjOWPdi0f0RbTuRrt5z0NMdMVlO8oNiBzhjTv6/vFJjPYEKOsCT3NwwxOvwJG1bccDCj9hRvlZkzn18IYboohGfn9gWjG8J8wf8CsXHHuhWbUZE1z/1r3hEY0JRaG9UdEjP2Y0WCS2bTQjlRmm+i7sBxCwbFp9rXXoHA1QCo/s/7oDiG/JIVTDYIRrypDCIEsjPagKp3dqZDAbCAEO2Tst5lAiC2nfhM0A7dHu736UUR8yw0OlLd8H6Rd97OQWjj+dSdGc+fjukOxHJ/E4pwv9avnCy1ct31VLYiTOQj0wCpbfPeFWx1uCmK/SIOnn
    template:
        metadata:
            creationTimestamp: null
            name: github-credentials
            namespace: argocd
        type: Opaque
