apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: demo-server-microservice
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    annotations:
        argocd-image-updater.argoproj.io/image-list: docker.io/archismanmridha/demo-server
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-credentials
        argocd-image-updater.argoproj.io/git-branch: main

spec:
    project: default

    source:
        repoURL: https://github.com/Archisman-Mridha/kubernetes-cicd
        targetRevision: HEAD
        path: kubernetes/microservices/demo-server

    destination:
        server: https://kubernetes.default.svc
        namespace: default

    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: true