apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: dockerhub-credentials
    namespace: argo
spec:
    encryptedData:
        config.json: AgB3ISfpZmz2Cp59wIHq7CzqHWWPxx/p/l71w2Eheo6DAJRZiGYxuQP/0lNxSk+sTdOEe3W/YrxV6GaHRbTO/bkgXmS+bQE5PQ7tpgqRw1NeGJd5J/kZWEDPxXNF1pUJR6Bq97zbzNeULtUvDSqEsHZjQuO3k69uRPD4HDqHtSQHgWjw13hYxMrsLtQcAY9M4AjwclYDPHOVfkE7mf3B7t3K7/lpt4vSySOiDbKlBZgIF19w077+MJf6BVMxsd50RXeVEkgdjGx2EjKPAaiQcOECTaiKTY1PHwX7zfqcBL2Xx5MthQRSH/pHgn4+JwDUynJOH8gMawaOWPVrxPOnI9eGGAlCKKlnnVYY2ji4cQP0UqRWe56Uv9PUOSCkqqhfnnID9jPobyUR4RXc40VcEprZrJvNtSn6RQkNetXzejEcaF5KwCXFg+VNDobJq8wdyjlxVDnagAnde6NsjIfwU5gDP3pLJXLf0HCGzn4uJR6rd3+78sN+MZG8qoLTGm9sXIl3LTcifNm4FnWJYv4mq3JYBkSfjSp0WVmhTO18ft7FlPF+5N9MCGvjKB7hAADRBqdLp6us8YXvn3h6Xqt8+53K5ViWYXaM4e/AoTlNQrGYSc6IYM2vWtZ7pcVesj3VjPZMARm5Ax1k6NQFMd6XpC0i+aWIXQOIX73KFF5M2/pXc7Obui59zxtZS1bI04r4W9srDQWCdOznfw0jvyP3W+HSE6k52gPBore2oS5niEGaQDbi4n4CSOlqkSGRSAIhZnZa6S6Hbh69ebYe2G3P05q1Av14ETDNBZXuj68iFJ+bftYPe60onTsdTtoLFTe9ThPs6sCFE4k6TrqxFIv9XmHAYnpMPwLD7Hl/xzVE/A==
    template:
        metadata:
            creationTimestamp: null
            name: dockerhub-credentials
            namespace: argo
        type: Opaque
