apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: argo-events-helm-installation
    namespace: argocd

spec:
    project: default

    destination:
        server: https://kubernetes.default.svc
        namespace: argo-events

    source:
        repoURL: https://argoproj.github.io/argo-helm
        chart: argo-events
        targetRevision: 2.0.10
        helm:
            releaseName: argo-events

    syncPolicy:
        syncOptions:
            - CreateNamespace=true
        automated:
            prune: true
            selfHeal: true